### ISSUE TITLE
Multi-nodes : not reading from archived logs for each node

### ISSUE THREAD

**Issue by Ersgersg** [eapowertools/qs-telemetry-dashboard#24] opened 2018-09-02 05:56 UTC
Hi
Even following the wiki for Multi-nodes, load script is not loading infos from the archived logs properly

issue seems to be with 
call DoDirSessionArchives ('$(vLogArchive)\$(vComputerName)\

which need to be replaced by 

call DoDirSessionArchives ('$(vLogArchive)\$(node1)\
call DoDirSessionArchives ('$(vLogArchive)\$(node2)\ 

so we are missing a loop around server name. Today i workaround with hardcoded servername but takingthe same principle as log monitor will be the solution

moreover in my environnement ComputerName =  SERVERA while the subdirectory below archived are SERVERA.domain.com

**Comment by Ersgersg** [comment] 2018-09-02 06:07
and the same to be done as well on the Perfarchives and QIXArchive section of course !

**Comment by Gutbuket** [comment] 2018-09-12 00:39
Thanks, I had the same problem in Sense June 2018 for ta single node. Hardcoding the FQDN fixed the problem. The problem is that the vComputerName variable uses the ComputerName function, which doesn't return the FQDN (hostname.domain.something) which is the directory name for the log files.

This can be fixed without hardcoding hostnames by adding the domain to the vComputerName variable in the Main section: Let vComputerName = ComputerName() & '.domain.somewhere';. I couldn't find how to call the FQDN in the script.

**Comment by jparis** [comment] 2018-10-05 16:38
This is all going through changes and 'should' be fixed for the 2.0 release.

**Closed** 2018-11-29 09:44 UTC
